version: '3.1'
services:
#    nginx:
#    image: nginx
#   container_name: nginx
#    ports:
#      - '80:80'
#      - '443:443'
#    networks:
#      - jenkins_network
#    links:
#      - jenkins
#    restart: always

  jenkins:
    image: jenkins
    container_name: jenkins
    ports:
      - '50000:50000'
      - '8080:8080'
    networks:
      - jenkins_network
    restart: always

networks:
  jenkins_network:
